// lib/lang.ts — Helper central de idioma para prompts de IA
// Importar en cualquier route.ts: import { getLangInstruction, getLocaleFromRequest } from '@/lib/lang'

export type Locale = 'es' | 'en'

/**
 * Lee el locale del request (body.locale > header x-locale > 'es')
 */
export function getLocaleFromRequest(request: Request, body?: any): Locale {
  const fromBody = body?.locale
  const fromHeader = request.headers.get('x-locale')
  const raw = fromBody || fromHeader || 'es'
  return raw === 'en' ? 'en' : 'es'
}

/**
 * Devuelve la instrucción de idioma para añadir al system prompt de la IA.
 * Si locale es 'en', fuerza respuesta en inglés profesional.
 * Si locale es 'es' o no especificado, no añade nada (comportamiento por defecto).
 */
export function getLangInstruction(locale?: string | null): string {
  if (locale === 'en') {
    return '\n\n[MANDATORY LANGUAGE RULE: You MUST write your ENTIRE response in professional English. Every word, every section, every label must be in English. No Spanish words allowed under any circumstances.]'
  }
  return ''
}

/**
 * Para documentos generados (DOCX): devuelve labels en el idioma correcto
 */
export function getDocLabels(locale: Locale) {
  if (locale === 'en') {
    return {
      patient: 'PATIENT',
      age: 'AGE',
      reportDate: 'REPORT DATE',
      evaluationType: 'EVALUATION TYPE',
      ageUnit: 'years old',
      notSpecified: 'Not specified',
      footer: 'This report was generated with the support of clinical artificial intelligence (ARIA - Vanty). It must be reviewed and signed by the responsible professional before delivery.',
      generated: 'Generated by Vanty — Neuropsychological Clinical Management System  |  Page ',
      of: ' of ',
    }
  }
  return {
    patient: 'PACIENTE',
    age: 'EDAD',
    reportDate: 'FECHA DEL INFORME',
    evaluationType: 'TIPO DE EVALUACIÓN',
    ageUnit: 'años',
    notSpecified: 'No especificada',
    footer: 'Este informe fue generado con el apoyo de inteligencia artificial clínica (ARIA - Vanty). Debe ser revisado y firmado por el profesional responsable antes de su entrega.',
    generated: 'Generado por Vanty — Sistema de Gestión Clínica Neuropsicológica  |  Página ',
    of: ' de ',
  }
}
